version: '3'

services:
  app:
    build: .
    restart: always
    privileged: true
    stdin_open: true
    working_dir: /root
    command: /bin/bash
    volumes:
      - .:/root
      - ~/.m2:/root/.m2
